(cl:defpackage kraken_msgs-srv
  (:use )
  (:export
   "SWITCHCONTROLLERS"
   "<SWITCHCONTROLLERS-REQUEST>"
   "SWITCHCONTROLLERS-REQUEST"
   "<SWITCHCONTROLLERS-RESPONSE>"
   "SWITCHCONTROLLERS-RESPONSE"
   "MOVEALONGLINE"
   "<MOVEALONGLINE-REQUEST>"
   "MOVEALONGLINE-REQUEST"
   "<MOVEALONGLINE-RESPONSE>"
   "MOVEALONGLINE-RESPONSE"
   "KRAKENRESETPOSE"
   "<KRAKENRESETPOSE-REQUEST>"
   "KRAKENRESETPOSE-REQUEST"
   "<KRAKENRESETPOSE-RESPONSE>"
   "KRAKENRESETPOSE-RESPONSE"
  ))

