(cl:in-package kraken_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BAT1_VOL-VAL
          BAT1_VOL
          BAT2_VOL-VAL
          BAT2_VOL
          BAT1_PERCENT_LEFT-VAL
          BAT1_PERCENT_LEFT
          BAT2_PERCENT_LEFT-VAL
          BAT2_PERCENT_LEFT
          BAT1_CURRENT-VAL
          BAT1_CURRENT
          BAT2_CUURENT-VAL
          BAT2_CUURENT
          THRUSTER_CURRENT-VAL
          THRUSTER_CURRENT
          KILLSWITCH_STATE-VAL
          KILLSWITCH_STATE
          MISSIONSWITCH_STATE-VAL
          MISSIONSWITCH_STATE
          DVL_CURRENT-VAL
          DVL_CURRENT
          IMU_CURRENT-VAL
          IMU_CURRENT
          DEPTH_SENSOR_CURRENT-VAL
          DEPTH_SENSOR_CURRENT
          SAFETY_SIGNAL-VAL
          SAFETY_SIGNAL
))