; Auto-generated. Do not edit!


(cl:in-package kraken_msgs-msg)


;//! \htmlinclude scanFeedback.msg.html

(cl:defclass <scanFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass scanFeedback (<scanFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <scanFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'scanFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kraken_msgs-msg:<scanFeedback> is deprecated: use kraken_msgs-msg:scanFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <scanFeedback>) ostream)
  "Serializes a message object of type '<scanFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <scanFeedback>) istream)
  "Deserializes a message object of type '<scanFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<scanFeedback>)))
  "Returns string type for a message object of type '<scanFeedback>"
  "kraken_msgs/scanFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'scanFeedback)))
  "Returns string type for a message object of type 'scanFeedback"
  "kraken_msgs/scanFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<scanFeedback>)))
  "Returns md5sum for a message object of type '<scanFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'scanFeedback)))
  "Returns md5sum for a message object of type 'scanFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<scanFeedback>)))
  "Returns full string definition for message of type '<scanFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'scanFeedback)))
  "Returns full string definition for message of type 'scanFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <scanFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <scanFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'scanFeedback
))
