/* Auto-generated by genmsg_cpp for file /home/dyutimoy/kinetic_workspace/kraken_3.0-indigo-devel/msgs_stack/kraken_msgs/msg/absoluteRPY.msg */
#ifndef KRAKEN_MSGS_MESSAGE_ABSOLUTERPY_H
#define KRAKEN_MSGS_MESSAGE_ABSOLUTERPY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kraken_msgs
{
template <class ContainerAllocator>
struct absoluteRPY_ {
  typedef absoluteRPY_<ContainerAllocator> Type;

  absoluteRPY_()
  : header()
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  absoluteRPY_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _roll_type;
  float roll;

  typedef float _pitch_type;
  float pitch;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::kraken_msgs::absoluteRPY_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::absoluteRPY_<ContainerAllocator>  const> ConstPtr;
}; // struct absoluteRPY
typedef  ::kraken_msgs::absoluteRPY_<std::allocator<void> > absoluteRPY;

typedef boost::shared_ptr< ::kraken_msgs::absoluteRPY> absoluteRPYPtr;
typedef boost::shared_ptr< ::kraken_msgs::absoluteRPY const> absoluteRPYConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::absoluteRPY_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::absoluteRPY_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::absoluteRPY_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::absoluteRPY_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::absoluteRPY_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e16d253ac46e3d525d41cd25c5023ecc";
  }

  static const char* value(const  ::kraken_msgs::absoluteRPY_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe16d253ac46e3d52ULL;
  static const uint64_t static_value2 = 0x5d41cd25c5023eccULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::absoluteRPY_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/absoluteRPY";
  }

  static const char* value(const  ::kraken_msgs::absoluteRPY_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::absoluteRPY_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::absoluteRPY_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kraken_msgs::absoluteRPY_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kraken_msgs::absoluteRPY_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::absoluteRPY_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct absoluteRPY_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::absoluteRPY_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::absoluteRPY_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_ABSOLUTERPY_H

