/* Auto-generated by genmsg_cpp for file /home/dyutimoy/kinetic_workspace/kraken_3.0-indigo-devel/msgs_stack/kraken_msgs/msg/scanGoal.msg */
#ifndef KRAKEN_MSGS_MESSAGE_SCANGOAL_H
#define KRAKEN_MSGS_MESSAGE_SCANGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace kraken_msgs
{
template <class ContainerAllocator>
struct scanGoal_ {
  typedef scanGoal_<ContainerAllocator> Type;

  scanGoal_()
  : direction(0)
  , speed(0.0)
  {
  }

  scanGoal_(const ContainerAllocator& _alloc)
  : direction(0)
  , speed(0.0)
  {
  }

  typedef int32_t _direction_type;
  int32_t direction;

  typedef float _speed_type;
  float speed;


  typedef boost::shared_ptr< ::kraken_msgs::scanGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::scanGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct scanGoal
typedef  ::kraken_msgs::scanGoal_<std::allocator<void> > scanGoal;

typedef boost::shared_ptr< ::kraken_msgs::scanGoal> scanGoalPtr;
typedef boost::shared_ptr< ::kraken_msgs::scanGoal const> scanGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::scanGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::scanGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::scanGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::scanGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::scanGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0181899c23ee952a295cdd8e12ba54de";
  }

  static const char* value(const  ::kraken_msgs::scanGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0181899c23ee952aULL;
  static const uint64_t static_value2 = 0x295cdd8e12ba54deULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::scanGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/scanGoal";
  }

  static const char* value(const  ::kraken_msgs::scanGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::scanGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal\n\
int32 direction		# +1 for Clockwise and -1 for Counter-clockwise\n\
float32 speed\n\
\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::scanGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::kraken_msgs::scanGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::scanGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.direction);
    stream.next(m.speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct scanGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::scanGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::scanGoal_<ContainerAllocator> & v) 
  {
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_SCANGOAL_H

