/* Auto-generated by genmsg_cpp for file /home/dyutimoy/kinetic_workspace/kraken_3.0-indigo-devel/msgs_stack/kraken_msgs/msg/setYawGoal.msg */
#ifndef KRAKEN_MSGS_MESSAGE_SETYAWGOAL_H
#define KRAKEN_MSGS_MESSAGE_SETYAWGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kraken_msgs
{
template <class ContainerAllocator>
struct setYawGoal_ {
  typedef setYawGoal_<ContainerAllocator> Type;

  setYawGoal_()
  : header()
  , yaw(0.0)
  {
  }

  setYawGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , yaw(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::kraken_msgs::setYawGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::setYawGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct setYawGoal
typedef  ::kraken_msgs::setYawGoal_<std::allocator<void> > setYawGoal;

typedef boost::shared_ptr< ::kraken_msgs::setYawGoal> setYawGoalPtr;
typedef boost::shared_ptr< ::kraken_msgs::setYawGoal const> setYawGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::setYawGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::setYawGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::setYawGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::setYawGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::setYawGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9bf551dc25a7d20a5398bb67204a99ca";
  }

  static const char* value(const  ::kraken_msgs::setYawGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9bf551dc25a7d20aULL;
  static const uint64_t static_value2 = 0x5398bb67204a99caULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::setYawGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/setYawGoal";
  }

  static const char* value(const  ::kraken_msgs::setYawGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::setYawGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
  # TODO: You can change the structure of this message if you need to.\n\
# goal definition\n\
Header header\n\
float32 yaw\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::setYawGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kraken_msgs::setYawGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kraken_msgs::setYawGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::setYawGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setYawGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::setYawGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::setYawGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_SETYAWGOAL_H

