/* Auto-generated by genmsg_cpp for file /home/dyutimoy/kinetic_workspace/kraken_3.0-indigo-devel/msgs_stack/kraken_msgs/msg/setYawFeedback.msg */
#ifndef KRAKEN_MSGS_MESSAGE_SETYAWFEEDBACK_H
#define KRAKEN_MSGS_MESSAGE_SETYAWFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kraken_msgs
{
template <class ContainerAllocator>
struct setYawFeedback_ {
  typedef setYawFeedback_<ContainerAllocator> Type;

  setYawFeedback_()
  : header()
  , Desired_yaw(0.0)
  , Current_yaw(0.0)
  , Error(0.0)
  {
  }

  setYawFeedback_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , Desired_yaw(0.0)
  , Current_yaw(0.0)
  , Error(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _Desired_yaw_type;
  float Desired_yaw;

  typedef float _Current_yaw_type;
  float Current_yaw;

  typedef float _Error_type;
  float Error;


  typedef boost::shared_ptr< ::kraken_msgs::setYawFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::setYawFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct setYawFeedback
typedef  ::kraken_msgs::setYawFeedback_<std::allocator<void> > setYawFeedback;

typedef boost::shared_ptr< ::kraken_msgs::setYawFeedback> setYawFeedbackPtr;
typedef boost::shared_ptr< ::kraken_msgs::setYawFeedback const> setYawFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::setYawFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::setYawFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::setYawFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::setYawFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::setYawFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7118c515219415471afc64514800b41f";
  }

  static const char* value(const  ::kraken_msgs::setYawFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7118c51521941547ULL;
  static const uint64_t static_value2 = 0x1afc64514800b41fULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::setYawFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/setYawFeedback";
  }

  static const char* value(const  ::kraken_msgs::setYawFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::setYawFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback\n\
Header header\n\
float32 Desired_yaw\n\
float32 Current_yaw\n\
float32 Error\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::setYawFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kraken_msgs::setYawFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kraken_msgs::setYawFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::setYawFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.Desired_yaw);
    stream.next(m.Current_yaw);
    stream.next(m.Error);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setYawFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::setYawFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::setYawFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Desired_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.Desired_yaw);
    s << indent << "Current_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.Current_yaw);
    s << indent << "Error: ";
    Printer<float>::stream(s, indent + "  ", v.Error);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_SETYAWFEEDBACK_H

