/* Auto-generated by genmsg_cpp for file /home/dyutimoy/kinetic_workspace/kraken_3.0-indigo-devel/msgs_stack/kraken_msgs/msg/setYawResult.msg */
#ifndef KRAKEN_MSGS_MESSAGE_SETYAWRESULT_H
#define KRAKEN_MSGS_MESSAGE_SETYAWRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace kraken_msgs
{
template <class ContainerAllocator>
struct setYawResult_ {
  typedef setYawResult_<ContainerAllocator> Type;

  setYawResult_()
  : header()
  , elapsed_time(0.0)
  {
  }

  setYawResult_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , elapsed_time(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _elapsed_time_type;
  float elapsed_time;


  typedef boost::shared_ptr< ::kraken_msgs::setYawResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kraken_msgs::setYawResult_<ContainerAllocator>  const> ConstPtr;
}; // struct setYawResult
typedef  ::kraken_msgs::setYawResult_<std::allocator<void> > setYawResult;

typedef boost::shared_ptr< ::kraken_msgs::setYawResult> setYawResultPtr;
typedef boost::shared_ptr< ::kraken_msgs::setYawResult const> setYawResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::kraken_msgs::setYawResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::kraken_msgs::setYawResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace kraken_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::setYawResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::kraken_msgs::setYawResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::kraken_msgs::setYawResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ef3316189818248cf37f7bbb749ff3fb";
  }

  static const char* value(const  ::kraken_msgs::setYawResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xef3316189818248cULL;
  static const uint64_t static_value2 = 0xf37f7bbb749ff3fbULL;
};

template<class ContainerAllocator>
struct DataType< ::kraken_msgs::setYawResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "kraken_msgs/setYawResult";
  }

  static const char* value(const  ::kraken_msgs::setYawResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::kraken_msgs::setYawResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# result definition\n\
Header header\n\
float32 elapsed_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::kraken_msgs::setYawResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::kraken_msgs::setYawResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::kraken_msgs::setYawResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::kraken_msgs::setYawResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.elapsed_time);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setYawResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kraken_msgs::setYawResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::kraken_msgs::setYawResult_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "elapsed_time: ";
    Printer<float>::stream(s, indent + "  ", v.elapsed_time);
  }
};


} // namespace message_operations
} // namespace ros

#endif // KRAKEN_MSGS_MESSAGE_SETYAWRESULT_H

